# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 01:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.CharField(default=b'', max_length=100, verbose_name=b'Goals')),
                ('organization', models.CharField(default=b'', max_length=100, verbose_name=b'University or Organization')),
                ('usage', models.CharField(choices=[(b'', b''), (b'student', b'Student'), (b'instructor', b'Instructor')], default=b'', max_length=10, verbose_name=b'Usage')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
