# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrainfo',
            name='favorite_editor',
        ),
        migrations.RemoveField(
            model_name='extrainfo',
            name='favorite_movie',
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='goals',
            field=models.CharField(default='', max_length=100, verbose_name=b'Goals using HydroLearn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='instructor',
            field=models.BooleanField(default=False, verbose_name=b'Instructor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='organization',
            field=models.CharField(default='', max_length=100, verbose_name=b'University or Organization Affiliation'),
            preserve_default=False,
        ),
    ]
