# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0003_auto_20190502_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='usage',
            field=models.CharField(choices=[(b'student', b'Student'), (b'instructor', b'Instructor')], default=b'', max_length=10, verbose_name=b'Usage'),
        ),
    ]
